/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useCylinder } from "@react-three/cannon"

useGLTF.preload("/Wheel.gltf")

const Wheel = forwardRef(({ radius = 0.7, leftSide, ...props }, ref) => {
  const group = useRef()
  const { nodes, materials } = useGLTF("/Wheel.gltf")
  useCylinder(() => ({ mass: 1, type: "Kinematic", rotation: [0, Math.PI * 0.75, 0], material: "wheel", collisionFilterGroup: 0, args: [radius, radius, 0.5, 16], ...props }), ref)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh ref={ref} geometry={nodes.xttiref_xttiref002.geometry} material={materials["xterra1__sub_.005"]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
    </group>
  )
})
export default Wheel
