/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useRef } from "react"
import { useGLTF } from "@react-three/drei"
import { useBox } from "@react-three/cannon"

useGLTF.preload("/Xterra.glb")

const Xterra = forwardRef(({ args = [1.7, 1, 4], mass = 500, ...props }, ref) => {
  const group = useRef()
  const { nodes, materials } = useGLTF("/Xterra.glb")
  const [, api] = useBox(() => ({ mass, args, allowSleep: false, onCollide: e => console.log("bonk"), ...props }), ref)
  return (
    <group api={api} ref={group} {...props} dispose={null}>
      <group position={[0.23, 0.02, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh castShadow receiveShadow geometry={nodes.xterra_xterra002.geometry} material={materials["xterra2__sub_.005"]} />
        <mesh castShadow receiveShadow geometry={nodes.xterra_xterra002_1.geometry} material={materials["xterra1__sub_.006"]} />
        <mesh castShadow receiveShadow geometry={nodes.xterra_xterra002_2.geometry} material={materials["xtgrey__sub_.005"]} />
        <mesh castShadow receiveShadow geometry={nodes.xterra_xterra002_3.geometry} material={materials["xtmirgls.005"]} />
        <mesh castShadow receiveShadow geometry={nodes.xterra_xterra002_4.geometry} material={materials["xtgrey2.005"]} />
        <mesh castShadow receiveShadow geometry={nodes.xterra_xterra002_5.geometry} material={materials["xtrakbot.005"]} />
      </group>
    </group>
  )
})

export default Xterra
